### ISSUE TITLE
Problem with limits example 3 in chapter 2

### ISSUE THREAD

**Issue by WilsonSawyer** [complex-analysis/complex-analysis.github.io#23]
I think there's a problem with example 3 in chapter 2, with both the
'D' and the D_2' domains. In short, I don't think that either has a
limit.

1. Let z=a+bi. Then f(z) = e^(a+bi) = (e^a)(e^(bi)). 
2. But then |f(z)| = e^a, since e^(bi) represents the argument/phase of f(z).
3. Using our limits definition, let's choose M=e^2. 
4. Now let's choose an arbitrarily-large R, which will go unspecified for now.
5. Let z = 1+Ri. Clearly |z| > R
6. But |f(z)| = e^1 = e, which is not going to surpass M, no matter how large 
   a value we choose for R.
We'll have a similar problem with D_2, since -1+Ri will circle zero without 
approaching it.

**Comment by jcponce** [comment]
Thanks. I will check it as soon as possible. :)

**Comment by jcponce** [comment]
Hi there,

After a closer inspection, there is a missing point in my definition. The value of R cannot be taken arbitrarily. This value must depend on the value we have chosen for M. Otherwise we have the issue you mentioned.

The same applies to the other definitions.

I think I will add that extra information in the definitions to clarify it. 

What do you think?

**Comment by jcponce** [comment]
Hi Wilson,

Thanks for your detailed explanation. I see better what is the issue with my example. I did not consider the case for a path parallel to the imaginary axis, since I missed the point that exp(z) is periodic. 

To avoid that issue in my example I need to add an extra restriction to the domain, e.g., considering |arg(z)|< delta < pi/2. 

What do you think?

**Comment by WilsonSawyer** [comment]
Yes, I think that's fine.
assuming that the example still serves your pedagogic purposes.

**Comment by jcponce** [comment]
Hi, 

I think I will change the example. 

Thanks again for the feedback.

Happy holidays. :)
